package Utils;

import org.apache.log4j.Logger;

public class Log {

   public static Logger log =  Logger.getLogger(Log.class.getName());




   // when the test case starts i should print the log
   public static void  startTestCase(String testCaseName){
      log.info("**************");
      log.info("**************");
      log.info("******"+ testCaseName + "*******");
   }
   // when my test stops i should print the log
   public static void endTestCase(String testCaseName){
      log.info("##########");
      log.info("##########");
      log.info("#########"+ testCaseName + "#########");
   }
   // if i want to print any message in between i should print the logs
   public static void info(String message){
      log.info(message);
   }

   public static void warning(String warning){
      log.info(warning);
   }


   //======================== MAVEN LIFECYCLE============
   // Maven Life Cycle: This consists of several phase
   //clean: removes all the files generated by the previous build
   //`
}
